//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlMyWayAddIn {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SqlMyWayOptionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SqlMyWayOptionSettings defaultInstance = ((SqlMyWayOptionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SqlMyWayOptionSettings())));
        
        public static SqlMyWayOptionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LineBreaks_BetweenStatements {
            get {
                return ((int)(this["LineBreaks_BetweenStatements"]));
            }
            set {
                this["LineBreaks_BetweenStatements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LineBreaks_BetweenClauses {
            get {
                return ((int)(this["LineBreaks_BetweenClauses"]));
            }
            set {
                this["LineBreaks_BetweenClauses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Capitalize_Keywords {
            get {
                return ((bool)(this["Capitalize_Keywords"]));
            }
            set {
                this["Capitalize_Keywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Capitalize_DataTypes {
            get {
                return ((bool)(this["Capitalize_DataTypes"]));
            }
            set {
                this["Capitalize_DataTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Capitalize_BuiltInFunctions {
            get {
                return ((bool)(this["Capitalize_BuiltInFunctions"]));
            }
            set {
                this["Capitalize_BuiltInFunctions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommaLists_Stacked {
            get {
                return ((bool)(this["CommaLists_Stacked"]));
            }
            set {
                this["CommaLists_Stacked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommaLists_TrailingCommas {
            get {
                return ((bool)(this["CommaLists_TrailingCommas"]));
            }
            set {
                this["CommaLists_TrailingCommas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Joins_Indented {
            get {
                return ((bool)(this["Joins_Indented"]));
            }
            set {
                this["Joins_Indented"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Joins_TableOnSameLine {
            get {
                return ((bool)(this["Joins_TableOnSameLine"]));
            }
            set {
                this["Joins_TableOnSameLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Joins_OnClauseOnSameLine {
            get {
                return ((bool)(this["Joins_OnClauseOnSameLine"]));
            }
            set {
                this["Joins_OnClauseOnSameLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Parentheses_SpacesOutside {
            get {
                return ((bool)(this["Parentheses_SpacesOutside"]));
            }
            set {
                this["Parentheses_SpacesOutside"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Parentheses_SpacesInside {
            get {
                return ((bool)(this["Parentheses_SpacesInside"]));
            }
            set {
                this["Parentheses_SpacesInside"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Semicolons_Add {
            get {
                return ((bool)(this["Semicolons_Add"]));
            }
            set {
                this["Semicolons_Add"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Comments_ExtraLineBeforeBlocks {
            get {
                return ((bool)(this["Comments_ExtraLineBeforeBlocks"]));
            }
            set {
                this["Comments_ExtraLineBeforeBlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Comments_ExtraLineAfterBlocks {
            get {
                return ((bool)(this["Comments_ExtraLineAfterBlocks"]));
            }
            set {
                this["Comments_ExtraLineAfterBlocks"] = value;
            }
        }
    }
}
